### PR TITLE
Fix multiline comments

### LINKED ISSUE #10: Frequent 422 Validation Failed on PR reviews
**Describe the bug**

**To Reproduce**
1. Create a PR review
2. Look at occasional error logs

```bash
2024-10-10T22:24:09-07:00 ERR Failed to add comment for filepath: /cmd/create.go error="error creating comment: POST https://api.github.com/repos/Mgla96/snappr/pulls/9/comments: 422 Validation Failed [{Resource:PullRequestReviewComment Field:pull_request_review_thread.path Code:invalid Message:} {Resource:PullRequestReviewComment Field:pull_request_review_thread.diff_hunk Code:missing_field Message:}]"
```

**Expected behavior**

Pull request comments should successfully be added on PRs.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Mgla96**
### Description

This PR decreases the % of 422 invalid Github requests when creating comments on PRs. It isn't perfect and we still get occasional 422s which we will need to continue to adderss.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

### Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### Related Issues

Fixes #10 

### How Has This Been Tested?

Running PR Review and verifying that majority of comments are passing validation and successfully being created. There is still more edge cases we'll need to handle.

```bash
./snappr-linux-amd64 review --prNumber 35 --commitSHA 3c25853ccdd63c61c892fe9e61f0f50d72ff46df --repository snappr --repositoryOwner Mgla96 --workflowName codeReview --fileRegexPattern "app.go$"
2024-10-15T23:56:37-07:00 INF added comment: Ensure to handle `clients.Side` types safely in `AddCommentToPullRequestReview` method to prevent potential runtime panics or issues arising from passing invalid or nil values.
2024-10-15T23:56:37-07:00 ERR Failed to add comment for filepath: internal/app/app.go error="error creating comment: github.PullRequestComment{Body:\"Good addition of considering `clients.Side` in `AddCommentToPullRequestReview`. This will help in differentiating between changes made in old and new file revisions in the diff.\", Path:\"internal/app/app.go\", Line:322, Side:\"RIGHT\", CommitID:\"3c25853ccdd63c61c892fe9e61f0f50d72ff46df\"}: POST https://api.github.com/repos/Mgla96/snappr/pulls/35/comments: 422 Validation Failed [{Resource:PullRequestReviewComment Field:pull_request_review_thread.line Code:custom Message:pull_request_review_thread.line must be part of the diff} {Resource:PullRequestReviewComment Field:pull_request_review_thread.diff_hunk Code:missing_field Message:}]"
2024-10-15T23:56:38-07:00 INF added comment: Please provide documentation comments for `PRReviewMap` and `PRCommentInfo` structures to improve code maintainability and understandability.
2024-10-15T23:56:39-07:00 INF added comment: The changes to the parameter of `StartSide` from `string` to `clients.Side` are helpful for type safety and clarity. Please confirm that all uses in the codebase have been properly refactored to this new type to avoid type mismatch.
```

### CODE REVIEW

File: internal/adapters/clients/github.go [hunk 1]
```diff
@@ -266,20 +255,20 @@ func (gc *GithubClient) GetCommitCode(context context.Context, owner, repo, comm
...
 		Path: github.String(path),
-		// Position in the diff where the comment should be applied
-		// Position: github.Int(position),
 		// First line of range you want to comment on
 		StartLine: github.Int(startLine),
 		// Last line of range you want to comment on
-		Line: github.Int(line),
+		Line:      github.Int(line),
+		Side:      github.String(string(side)),
+		StartSide: github.String(string(startSide)),
```
Comment (Mgla96) [inline internal/adapters/clients/github.go]: Consider aligning the alignment of the struct fields to improve code readability. Conventionally, Go code aligns the field names and types.

File: internal/adapters/clients/github.go [hunk 2]
```diff
@@ -266,20 +255,20 @@ func (gc *GithubClient) GetCommitCode(context context.Context, owner, repo, comm
...
 	}
```
Comment (Mgla96) [inline internal/adapters/clients/github.go]: Ensure alignment of parameters for better readability.

File: internal/adapters/clients/github.go [hunk 3]
```diff
@@ -266,20 +255,20 @@ func (gc *GithubClient) GetCommitCode(context context.Context, owner, repo, comm
...
 		// Filepath which the comment applies
 		Path: github.String(path),
-		// Position in the diff where the comment should be applied
-		// Position: github.Int(position),
 		// First line of range you want to comment on
 		StartLine: github.Int(startLine),
 		// Last line of range you want to comment on
-		Line: github.Int(line),
+		Line:      github.Int(line),
+		Side:      github.String(string(side)),
```
Comment (Mgla96) [inline internal/adapters/clients/github.go]: Good addition of SubjectType to clarify the type of the subject for the PR comment. This makes the comment context clearer in API requests.

File: internal/app/app.go [hunk 4]
```diff
@@ -79,11 +79,18 @@ type FileChange struct {
...
 
+// PRReviewMap is a map of file paths to a list of PRCommentInfo
 type PRReviewMap map[string][]PRCommentInfo
 type PRCommentInfo struct {
 	CommentBody string
-	StartLine   int
-	Line        int
+	// The start_line is the first line in the pull request diff that your multi-line comment applies to.
+	StartLine int
+	// The line of the blob in the pull request diff that the comment applies to. For a multi-line comment, the last line of the range that your comment applies to.
```
Comment (Mgla96) [inline internal/app/app.go:88]: It is good practice to include documentation for newly introduced properties in a struct. This helps other developers understand the purpose and usage of these properties.

Comment (Mgla96) [inline internal/app/app.go:88]: For the added `Side` and `StartSide` fields in the `PRCommentInfo` struct, consider adding enum validations if applicable to restrict the values to only 'LEFT' or 'RIGHT'.

File: internal/app/app.go [hunk 5]
```diff
@@ -37,7 +37,7 @@ type githubClient interface {
 	GetLatestCommitFromBranch(ctx context.Context, owner, repo, branch string) (string, error)
```
Comment (Mgla96) [inline internal/app/app.go:37]: Ensure to document the new parameters `startSide` and `side` in the interface method to clarify their usage and requirements.

File: internal/app/app.go [hunk 6]
```diff
@@ -79,11 +79,18 @@ type FileChange struct {
...
 }
 
+// PRReviewMap is a map of file paths to a list of PRCommentInfo
 type PRReviewMap map[string][]PRCommentInfo
 type PRCommentInfo struct {
 	CommentBody string
-	StartLine   int
-	Line        int
+	// The start_line is the first line in the pull request diff that your multi-line comment applies to.
+	StartLine int
```
Comment (Mgla96) [inline internal/app/app.go:87]: Consider adding more detailed comments to newly added constants, explaining their purpose or usage across the application.

File: internal/app/app.go (hunk 5 above)
Comment (Mgla96) [inline internal/app/app.go:37]: Good addition to include both `startSide` and `side` in the method signature for `AddCommentToPullRequestReview`. This change ensures that the comments can be correctly placed in the diff context of the PR, whether they relate to the left side (base) or the right side (compare).

File: internal/app/app.go (hunk 6 above)
Comment (Mgla96) [inline internal/app/app.go:87]: It is key that the type of `StartSide` is consistent. Changing from `string` to `clients.Side` matches the existing type for `Side` thus avoiding type inconsistencies and potential bugs.

File: internal/app/app.go [hunk 7]
```diff
@@ -79,11 +79,18 @@ type FileChange struct {
 	Patch       string `json:"patch"`
```
Comment (Mgla96) [inline internal/app/app.go:79]: Adding documentation for `PRReviewMap` is useful for maintaining the codebase. However, ensure that the comment explicitly describes the purpose and usage of the structure for better clarity.

File: internal/app/app.go (hunk 5 above)
Comment (Mgla96) [inline internal/app/app.go:37]: Ensure to handle `clients.Side` types safely in `AddCommentToPullRequestReview` method to prevent potential runtime panics or issues arising from passing invalid or nil values.

File: internal/app/app.go (hunk 7 above)
Comment (Mgla96) [inline internal/app/app.go:79]: Please provide documentation comments for `PRReviewMap` and `PRCommentInfo` structures to improve code maintainability and understandability.
